Taller ANN Multiclass

In [1]:
##importar librerias


import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [2]:
# cargar el dataset  

url = "https://github.com/adiacla/bigdata/raw/master/riesgo.xlsx"

df = pd.read_excel(url)

df.head()

,Customer_ID,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,CUS_0x1000,Alistair Barrf,17.375,913-74-1218,Lawyer,30625.94,2706.161667,6.0,5.0,27,...,Bad,1562.91,33.477546,10.458333,Yes,42.941090,158.549735,High_spent_Medium_value_payments,335.375341,0
1,CUS_0x1009,Arunah,25.750,063-67-6938,Mechanic,52312.68,4250.390000,6.0,5.0,17,...,Standard,202.68,29.839984,30.714286,Yes,108.366467,146.679378,High_spent_Medium_value_payments,428.743155,1
2,CUS_0x100b,Shirboni,18.500,238-62-0395,Media_Manager,113781.39,9549.782500,1.0,4.0,1,...,Good,1030.20,34.841449,15.571429,No,0.000000,505.386526,High_spent_Large_value_payments,781.229776,0
3,CUS_0x1011,Schneyerh,43.875,793-05-8223,Doctor,58918.47,5208.872500,3.0,3.0,17,...,Standard,473.14,27.655897,15.541667,Yes,123.434939,311.060914,Low_spent_Medium_value_payments,332.642837,1
4,CUS_0x1013,Cameront,43.750,930-49-9615,Mechanic,98620.98,7962.415000,3.0,3.0,6,...,Good,1233.51,31.933940,17.535714,No,228.018084,355.442408,High_spent_Medium_value_payments,472.781009,1

In [3]:

# 2. exploracion de datos 


# Mostrar información general del dataset
# (tipos de datos, valores nulos, etc.)
df.info()

# Mostrar estadísticas básicas de las variables numéricas
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               12500 non-null  object
 1   Name                      12500 non-null  object
 2   Age                       12500 non-null  float64
 3   SSN                       12500 non-null  object
 4   Occupation                12500 non-null  object
 5   Annual_Income             12500 non-null  float64
 6   Monthly_Inhand_Salary     12500 non-null  float64
 7   Num_Bank_Accounts         12500 non-null  float64
 8   Num_Credit_Card           12500 non-null  float64
 9   Interest_Rate             12500 non-null  int64
 10  Num_of_Loan               12500 non-null  int64
 11  Type_of_Loan              11074 non-null  object
 12  Delay_from_due_date       12500 non-null  float64
 13  Num_of_Delayed_Payment    12500 non-null  float64
 14  Changed_Credit_Limit      12500 non-null  float64
 15  Num_Credit_Inquiries      12500 non-null  float64
 16  Credit_Mix                12500 non-null  object
 17  Outstanding_Debt          12500 non-null  float64
 18  Credit_Utilization_Ratio  12500 non-null  float64
 19  Credit_History_Age        12500 non-null  float64
 20  Payment_of_Min_Amount     12500 non-null  object
 21  Total_EMI_per_month       12500 non-null  float64
 22  Amount_invested_monthly   12500 non-null  float64
 23  Payment_Behaviour         12500 non-null  object
 24  Monthly_Balance           12500 non-null  float64
 25  Credit_Score              12500 non-null  int64
dtypes: float64(15), int64(3), object(8)
memory usage: 2.5+ MB

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Credit_Score
count,12500.000000,12500.000000,12500.000000,12500.000000,12500.00000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000,12500.000000
mean,33.311294,50505.123449,4198.468568,5.368828,5.53362,14.532080,3.532880,21.068780,13.338642,10.465068,5.779694,1426.220376,32.285069,18.433820,107.698610,195.751837,403.120320,0.845200
std,10.760177,38300.762656,3187.142979,2.592493,2.06604,8.741636,2.446442,14.772965,6.153148,6.445141,3.707936,1155.169458,2.060154,8.304817,118.990964,136.847120,175.476887,0.697994
min,14.000000,7005.930000,303.645417,0.000000,0.50000,1.000000,0.000000,-2.000000,0.000000,0.500000,0.000000,0.230000,25.476634,0.375000,0.000000,14.528879,92.841401,0.000000
25%,24.415179,19342.972500,1625.744479,3.000000,4.00000,7.000000,2.000000,9.875000,9.000000,5.493750,3.000000,566.072500,30.854492,12.041667,30.333649,97.690749,284.546710,0.000000
50%,33.000000,36999.705000,3097.016667,5.375000,5.00000,13.000000,3.000000,17.875000,13.750000,9.370000,5.250000,1166.155000,32.241830,18.238095,68.102176,152.081485,338.491580,1.000000
75%,41.750000,71683.470000,5961.664375,7.000000,7.00000,20.000000,5.000000,28.000000,18.175000,14.656250,8.500000,1945.962500,33.600168,25.125000,151.220882,257.566585,465.372970,1.000000
max,56.000000,179987.280000,15204.633333,10.500000,10.87500,34.000000,9.000000,63.250000,26.375000,31.115000,16.375000,4998.070000,42.395301,33.380952,1515.158986,1005.847285,1349.264887,2.000000

In [4]:

# 3. eliminacion de columnas irrelevantes

df = df.drop(columns=['Customer_ID', 'Name', 'SSN'])

In [5]:

# 4. codificacion de variables categoricas
# Se crea un codificador de etiquetas
le = LabelEncoder()

# Se recorren todas las columnas que sean tipo texto
for col in df.select_dtypes(include='object').columns:
    
    # Se convierten a string y luego a valores numéricos
    df[col] = le.fit_transform(df[col].astype(str))

In [6]:

# 5. separar features y target


# Variables predictoras (features)
X = df.drop('Credit_Score', axis=1)

# Variable objetivo (target)
y = df['Credit_Score']

In [7]:

# 6. normalizacion

# Se crea el escalador
scaler = StandardScaler()

# Se normalizan las variables predictoras
X_scaled = scaler.fit_transform(X)

In [8]:

# 7. reduccion de dimencionalidad (PCA)


# Se crea el modelo PCA para reducir a 10 componentes principales
pca = PCA(n_components=10)

# Se transforman los datos escalados
X_pca = pca.fit_transform(X_scaled)

# Mostrar cuánta varianza explica cada componente
print("Varianza explicada por cada componente:")
print(pca.explained_variance_ratio_)

Varianza explicada por cada componente:
[0.35172237 0.15162003 0.05606456 0.0534983  0.04556861 0.04114824
 0.03891659 0.03669029 0.03308568 0.02816329]

In [9]:

# 8. Division de datos 


# Se divide el dataset:
# 80% para entrenamiento
# 20% para pruebas
X_train, X_test, y_train, y_test = train_test_split(
    X_pca,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:

# 9. ONE HOT ENCODING del target

# Como tenemos 3 clases (0,1,2)
# se convierten a formato categórico

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [11]:

# 10. creacion del modelo ANN


# Se crea un modelo secuencial
model = Sequential()

# Capa de entrada + primera capa oculta
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))

# Segunda capa oculta
model.add(Dense(32, activation='relu'))

# Capa de salida
# 3 neuronas porque hay 3 clases
# Softmax se usa para clasificación multiclase
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:

# 11. compilacion del modelo


model.compile(
    optimizer='adam',                 # algoritmo de optimización
    loss='categorical_crossentropy',  # función de pérdida para multiclase
    metrics=['accuracy']              # métrica de evaluación
)

In [13]:

# 12. entrenamiento del modelo


history = model.fit(
    X_train,
    y_train,
    epochs=50,          # número de iteraciones de entrenamiento
    batch_size=32,      # tamaño de lote
    validation_split=0.2
)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6223 - loss: 0.8355 - val_accuracy: 0.6970 - val_loss: 0.6877
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7058 - loss: 0.6564 - val_accuracy: 0.6905 - val_loss: 0.6785
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7098 - loss: 0.6456 - val_accuracy: 0.7055 - val_loss: 0.6692
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7189 - loss: 0.6436 - val_accuracy: 0.6995 - val_loss: 0.6702
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7188 - loss: 0.6398 - val_accuracy: 0.6990 - val_loss: 0.6673
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7229 - loss: 0.6327 - val_accuracy: 0.7120 - val_loss: 0.6611
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7247 - loss: 0.6281 - val_accuracy: 0.7080 - val_loss: 0.6636
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7172 - loss: 0.6253 - val_accuracy: 0.7115 - val_loss: 0.6585
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7194 - loss: 0.6247 - val_accuracy: 0.7130 - val_loss: 0.6602
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7305 - loss: 0.6142 - val_accuracy: 0.7125 - val_loss: 0.6598
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7348 - loss: 0.6107 - val_accuracy: 0.7070 - val_loss: 0.6597
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7356 - loss: 0.6083 - val_accuracy: 0.7115 - val_loss: 0.6689
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7320 - loss: 0.6209 - val_accuracy: 0.7105 - val_loss: 0.6651
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7418 - loss: 0.6031 - val_accuracy: 0.7185 - val_loss: 0.6571
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7295 - loss: 0.6071 - val_accuracy: 0.7110 - val_loss: 0.6605
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7376 - loss: 0.5957 - val_accuracy: 0.7085 - val_loss: 0.6587
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7419 - loss: 0.5946 - val_accuracy: 0.7115 - val_loss: 0.6543
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7354 - loss: 0.6002 - val_accuracy: 0.7135 - val_loss: 0.6730
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7352 - loss: 0.6121 - val_accuracy: 0.7015 - val_loss: 0.6719
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7392 - loss: 0.6018 - val_accuracy: 0.7145 - val_loss: 0.6549
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7337 - loss: 0.5979 - val_accuracy: 0.7015 - val_loss: 0.6699
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7442 - loss: 0.5899 - val_accuracy: 0.7040 - val_loss: 0.6630
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7402 - loss: 0.5935 - val_accuracy: 0.7015 - val_loss: 0.6666
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7346 - loss: 0.6013 - val_accuracy: 0.7110 - val_loss: 0.6681
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7409 - loss: 0.5957 - val_accuracy: 0.7095 - val_loss: 0.6651
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7429 - loss: 0.5898 - val_accuracy: 0.7030 - val_loss: 0.6757
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7453 - loss: 0.5860 - val_accuracy: 0.7140 - val_loss: 0.6657
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7502 - loss: 0.5741 - val_accuracy: 0.7160 - val_loss: 0.6629
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7407 - loss: 0.5961 - val_accuracy: 0.7125 - val_loss: 0.6632
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7491 - loss: 0.5705 - val_accuracy: 0.7145 - val_loss: 0.6690
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7520 - loss: 0.5695 - val_accuracy: 0.7040 - val_loss: 0.6677
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7437 - loss: 0.5679 - val_accuracy: 0.7060 - val_loss: 0.6667
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7404 - loss: 0.5831 - val_accuracy: 0.7070 - val_loss: 0.6748
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7471 - loss: 0.5707 - val_accuracy: 0.6985 - val_loss: 0.6711
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7340 - loss: 0.5891 - val_accuracy: 0.7030 - val_loss: 0.6839
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7442 - loss: 0.5801 - val_accuracy: 0.7010 - val_loss: 0.6856
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7420 - loss: 0.5806 - val_accuracy: 0.7105 - val_loss: 0.6710
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7450 - loss: 0.5784 - val_accuracy: 0.7135 - val_loss: 0.6793
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7460 - loss: 0.5684 - val_accuracy: 0.7045 - val_loss: 0.6799
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7538 - loss: 0.5673 - val_accuracy: 0.7150 - val_loss: 0.6800
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7462 - loss: 0.5818 - val_accuracy: 0.7120 - val_loss: 0.6839
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7445 - loss: 0.5750 - val_accuracy: 0.7070 - val_loss: 0.6858
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7584 - loss: 0.5608 - val_accuracy: 0.7040 - val_loss: 0.6826
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7465 - loss: 0.5723 - val_accuracy: 0.7025 - val_loss: 0.6835
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7510 - loss: 0.5556 - val_accuracy: 0.6905 - val_loss: 0.6846
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7487 - loss: 0.5654 - val_accuracy: 0.7150 - val_loss: 0.6881
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7531 - loss: 0.5615 - val_accuracy: 0.6980 - val_loss: 0.6932
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7471 - loss: 0.5579 - val_accuracy: 0.7065 - val_loss: 0.6863
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7542 - loss: 0.5617 - val_accuracy: 0.6990 - val_loss: 0.6881
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7529 - loss: 0.5611 - val_accuracy: 0.7205 - val_loss: 0.6909

In [14]:

# 13. evaluacion del modelo


# Evaluar el modelo con los datos de prueba
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy del modelo:", accuracy)

79/79 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7177 - loss: 0.6822
Accuracy del modelo: 0.7239999771118164

In [15]:

# 15. predicciones

# Se obtienen las probabilidades predichas
y_pred = model.predict(X_test)

# Se convierten a la clase con mayor probabilidad
y_pred = np.argmax(y_pred, axis=1)

# Convertir los valores reales
y_true = np.argmax(y_test, axis=1)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [16]:

# 16. matriz de confusion

print(confusion_matrix(y_true, y_pred))

[[539 200  83]
 [128 917 172]
 [ 25  82 354]]

In [17]:

# 17. reporte de clasificacion


print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.66      0.71       822
           1       0.76      0.75      0.76      1217
           2       0.58      0.77      0.66       461

    accuracy                           0.72      2500
   macro avg       0.71      0.73      0.71      2500
weighted avg       0.74      0.72      0.73      2500

In [ ]:
print("Clientes en X:", X.shape[0])
print("Clientes en y:", y.shape[0])